-- Cache dung (cach_dung) cho 254 option - tra tu code server: NPoint.addOption, SetClothes,
-- InventoryService (optionCanUpgrade, isItemIncrementalOption, powerRequire), Trade, ConsignShopService...
-- Chi UPDATE cach_dung, khong dot ten_viet/goi_y/min_param/max_param.
SET NAMES utf8mb4;

INSERT INTO panel_option_dict (option_id, cach_dung) VALUES
(0, 'Công dụng: cộng thẳng sức đánh cơ bản (NPoint.addOption case 0: dameAdd += param). Cách dùng: param = số SĐ cộng thêm, thường 500-20000. Điều kiện: trang bị đang mặc, Card hoặc Cung Mệnh.'),
(1, 'Công dụng: thời gian hiệu lực theo phút; server cộng dồn param của option 1 khi gộp 2 vật phẩm trùng template vào hành trang (InventoryService.isItemIncrementalOption). Cách dùng: param = số phút. Điều kiện: vật phẩm cộng dồn kiểu tự luyện tập/bí kiếp.'),
(2, 'Công dụng: cộng HP và KI (NPoint case 2: hp/mp += param x1000). Cách dùng: param theo nghìn, vd 50 = +50.000 HP và +50.000 KI. Điều kiện: trang bị đang mặc.'),
(3, 'Công dụng: vô hiệu một phần sát thương chưởng và chuyển thành KI (NPoint case 3: voHieuChuong += param). Cách dùng: param = % sát thương chưởng được vô hiệu/chuyển KI. Điều kiện: trang bị đang mặc.'),
(4, 'Công dụng: hồi % KI mỗi lần bị đánh trúng (xử lý lúc chịu sát thương). Cách dùng: param = % KI hồi. Điều kiện: trang bị đang mặc; không nằm trong NPoint.addOption.'),
(5, 'Công dụng: tăng % sức đánh chí mạng (NPoint case 5: tlDameCrit và tlSDCM += param). Cách dùng: param = % STCM, thường 1-100. Điều kiện: trang bị đang mặc/Card/Cung Mệnh.'),
(6, 'Công dụng: cộng HP sinh lực (NPoint case 6: hpAdd += param). Cách dùng: param = số HP cộng thêm. Điều kiện: trang bị đang mặc.'),
(7, 'Công dụng: cộng KI (NPoint case 7: mpAdd += param). Cách dùng: param = số KI cộng thêm. Điều kiện: trang bị đang mặc.'),
(8, 'Công dụng: hút % HP và KI của người xung quanh mỗi 5 giây (NPoint case 8: tlHutHpMpXQ). Cách dùng: param = % hút. Điều kiện: trang bị đang mặc, tự động chu kỳ 5 giây.'),
(9, 'Công dụng: đánh dấu thời gian hiệu lực; server dùng param lớn hơn 0 làm cờ đang hiệu lực (vd giáp tập luyện type 32: NPoint.setDameTrainArmor cộng % SĐ theo getPercentTrainArmor). Cách dùng: param = số phút, lớn hơn 0 = còn hiệu lực.'),
(10, 'Ghi chú: option 10 không còn trong NPoint.addOption - chủ yếu hiển thị trên client. Muốn cộng chính xác thật hãy dùng option 18 (tlchinhxac). Cách dùng: param = điểm chính xác hiển thị.'),
(11, 'Công dụng: đánh dấu số Công Đức trên vật phẩm (điểm thưởng dùng cho NPC/shop Công Đức). Cách dùng: param = số công đức. Điều kiện: hiển thị, không cộng chỉ số trực tiếp.'),
(12, 'Công dụng: đếm số lần sử dụng còn lại; khi param về 0 vật phẩm bị xóa khỏi hành trang (InventoryService.subParamItemsBag). Cách dùng: param = số lần. Điều kiện: vật phẩm tiêu hao.'),
(13, 'Công dụng: thống kê số yêu quái đã hạ gắn trên vật phẩm (nhiệm vụ/sự kiện). Cách dùng: param = số quái đã hạ. Điều kiện: hiển thị, không cộng chỉ số.'),
(14, 'Công dụng: cộng % chí mạng (NPoint case 14: critAdd += param). Cách dùng: param = % chí mạng, khuyến nghị 1-25. Điều kiện: trang bị đang mặc.'),
(15, 'Ghi chú: không có trong NPoint.addOption - chủ yếu hiển thị. Phản đòn cận chiến thật dùng option 97 (tlPST). Cách dùng: param = số/% phản đòn hiển thị.'),
(16, 'Công dụng: tăng tốc độ di chuyển (NPoint case 16: tlSpeed += param; speed = 6 + 6 x tlSpeed/100). Cách dùng: param = %, cứ mỗi 100 cộng thêm thì chạy nhanh hơn 1 cấp. Điều kiện: trang bị đang mặc.'),
(17, 'Ghi chú: không có trong NPoint.addOption - hiển thị. Né đòn thật dùng option 108 (tlNeDon). Cách dùng: param = điểm né đòn hiển thị.'),
(18, 'Công dụng: cộng % chính xác (NPoint case 18: tlchinhxac += param). Cách dùng: param = % chính xác. Điều kiện: trang bị đang mặc.'),
(19, 'Công dụng: cộng % tấn công thêm khi đánh quái (NPoint case 19: tlDameAttMob). Cách dùng: param = %, cộng dồn nhiều item. Điều kiện: chỉ áp dụng khi đánh quái, không áp khi đánh người.'),
(20, 'Công dụng: hiển thị PIN của vật phẩm cần năng lượng (vd vệ tinh/phụ kiện). Cách dùng: param = lượng PIN còn lại. Điều kiện: hiển thị, không cộng chỉ số.'),
(21, 'Công dụng: yêu cầu sức mạnh khi mặc (InventoryService: powerRequire = param x 1.000.000.000). Cách dùng: param tính theo TỈ, vd 18 = yêu cầu 18 tỉ SM. Điều kiện: sức mạnh chưa đủ thì không mặc được; SetClothes: param = 80 được đếm vào set ĐHĐ.'),
(22, 'Công dụng: cộng HP (NPoint case 22: hpAdd += param x1000). Cách dùng: param theo NGHÌN, vd 500 = +500.000 HP. Điều kiện: trang bị đang mặc; option ĐƯỢC NÂNG CẤP (InventoryService.optionCanUpgrade).'),
(23, 'Công dụng: cộng KI (NPoint case 23: mpAdd += param x1000). Cách dùng: param theo NGHÌN. Điều kiện: trang bị đang mặc; option ĐƯỢC NÂNG CẤP (optionCanUpgrade).'),
(24, 'Công dụng: cờ hiệu ứng - tăng trọng lực, làm chậm mọi người xung quanh (NPoint case 24: isLamCham). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm có hiệu ứng này.'),
(25, 'Công dụng: cờ hiệu ứng - tàng hình mỗi 5 giây (NPoint case 25: isTanHinh). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm.'),
(26, 'Công dụng: cờ hiệu ứng - hóa đá người xung quanh mỗi 30 giây (NPoint case 26: isHoaDa). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm.'),
(27, 'Công dụng: hồi HP định kỳ (NPoint case 27: hpHoiAdd; nhận mỗi 30 giây). Cách dùng: param = số HP hồi thêm mỗi 30s. Điều kiện: mặc; option ĐƯỢC NÂNG CẤP (optionCanUpgrade).'),
(28, 'Công dụng: hồi KI định kỳ (NPoint case 28: mpHoiAdd; nhận mỗi 30 giây). Cách dùng: param = số KI hồi thêm mỗi 30s. Điều kiện: mặc; option ĐƯỢC NÂNG CẤP (optionCanUpgrade).'),
(29, 'Công dụng: hiệu ứng - biến người xung quanh thành Sôcôla mỗi 30 giây (sự kiện). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm sự kiện.'),
(30, 'Công dụng: cờ Đã khóa - vật phẩm có option 30 (hoặc 218) KHÔNG giao dịch được (Trade.java). Cách dùng: param 1. Điều kiện: làm cờ khóa đồ; nhiều event gán 30 để chặn giao dịch.'),
(31, 'Công dụng: số lượng cộng dồn - server gộp param khi xếp chồng item trùng template (isItemIncrementalOption, vd bí kiếp). Cách dùng: param = số lượng. Điều kiện: gộp item cùng loại vào hành trang.'),
(32, 'Công dụng: cờ miễn nhiễm - người mang không bị hóa Xương (sự kiện). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm có option.'),
(33, 'Công dụng: cờ dịch chuyển tức thời - NPoint case 33: teleport = true khi mặc. Cách dùng: param 0/1. Điều kiện: mặc vật phẩm được bật cờ dịch chuyển.'),
(34, 'Công dụng: đếm mảnh Tinh An - NPoint: đủ 5 món (setTinhAn >= 5) bật hiệu ứng Tinh An. Cách dùng: param 0/1, mỗi món đếm 1 lần. Điều kiện: mặc đủ 5 món có option này.'),
(35, 'Công dụng: đếm mảnh Nguyệt An - đủ 5 món (setNguyetAn >= 5) bật hiệu ứng Nguyệt An. Cách dùng: param 0/1. Điều kiện: mặc đủ 5 món.'),
(36, 'Công dụng: đếm mảnh Nhật An - đủ 5 món (setNhatAn >= 5) bật hiệu ứng Nhật An. Cách dùng: param 0/1. Điều kiện: mặc đủ 5 món.'),
(37, 'Công dụng: thống kê số lần đã ký gửi của vật phẩm (type 4). Cách dùng: param = số lần ký gửi. Điều kiện: hiển thị, không cộng chỉ số.'),
(38, 'Công dụng: option điều kiện - chỉ phát huy tác dụng khi người chơi đang HỢP THỂ. Cách dùng: param 0/1. Điều kiện: đang hợp thể (fusion).'),
(39, 'Công dụng: hiển thị % bạo kích sức đánh chưởng (STCM). Cách dùng: param = % bạo kích. Điều kiện: type 6; cộng chí mạng thật server dùng option 5/14 - kiểm tra param hợp lý trước khi cấp.'),
(40, 'Công dụng: đánh dấu số đá ngũ sắc đã nạp cho Siêu Cải Trang (tiêu chí nâng siêu cải trang). Cách dùng: param = số đá. Điều kiện: dùng trên cải trang, hiển thị/điều kiện nâng.'),
(41, 'Công dụng: nhãn Chỉ số thưởng - hiển thị chỉ số thưởng thêm của vật phẩm (khảm đá/set). Cách dùng: param = giá trị thưởng. Điều kiện: hiển thị, không cộng riêng trong NPoint.'),
(42, 'Công dụng: nhãn % Khảm Đá cho Sức Đánh. Cách dùng: param = % sau khảm. Ghi chú: case 42-46 trong NPoint.addOption đang bị comment - server không cộng thẳng, chỉ hiển thị.'),
(43, 'Công dụng: nhãn % Khảm Đá cho HP. Cách dùng: param = %. Ghi chú: NPoint case 43 đang comment - không cộng thẳng.'),
(44, 'Công dụng: nhãn % Khảm Đá cho KI. Cách dùng: param = %. Ghi chú: NPoint case 44 đang comment - không cộng thẳng.'),
(45, 'Công dụng: nhãn % Khảm Đá cho GIÁP. Cách dùng: param = %. Ghi chú: NPoint case 45 đang comment - không cộng thẳng.'),
(46, 'Công dụng: nhãn % Khảm Đá cho Bạo Kích. Cách dùng: param = %. Ghi chú: NPoint case 46 đang comment - không cộng thẳng.'),
(47, 'Công dụng: cộng giáp/DEF (NPoint case 47: defAdd += param). Cách dùng: param = số giáp cộng thêm, thường 100-5000. Điều kiện: mặc; option ĐƯỢC NÂNG CẤP (optionCanUpgrade).'),
(48, 'Công dụng: cộng cả HP và KI (NPoint case 48: hpAdd và mpAdd += param, đơn vị thường). Cách dùng: param = số HP và KI cộng thêm. Điều kiện: mặc.'),
(49, 'Công dụng: tăng % sức đánh (NPoint case 49/50: tlDame += param x opt49_factor/100, hệ số mặc định 10). Cách dùng: param = % theo tên; server thực nhận khoảng param chia 10 (% SĐ) - test trước khi cấp lớn. Điều kiện: mặc.'),
(50, 'Công dụng: tăng % sức đánh (NPoint case 50: tlDame += param x opt49_factor/100, mặc định 10). Cách dùng: param = %; thực nhận khoảng param chia 10 (% SĐ). Điều kiện: mặc/Card/Cung Mệnh.'),
(51, 'Công dụng: bộ Sét Broly - SetClothes đếm option trên 5 slot đầu, đủ 5/5 kích hoạt +25% Giảm ST (theo tên). Cách dùng: param 0/1/món, trùng trong 1 món chỉ đếm 1. Điều kiện: mặc đủ 5/5.'),
(52, 'Công dụng: bộ Sét Picolo - +500% KI khi đủ 5/5 (SetClothes.setpicolo). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5 trên 5 slot đầu.'),
(53, 'Công dụng: bộ Sét Vegeta - +500% HP khi đủ 5/5 (SetClothes.setvegeta). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(54, 'Công dụng: bộ Sét Goku - +80% SD khi đủ 5/5 (SetClothes.setgoku). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(55, 'Công dụng: bộ Sét Phụ Hồ - +8888% TNSM khi đủ 5/5 (SetClothes.setphuho). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(56, 'Công dụng: bộ Sét Mabu - +25% Chí Mạng khi đủ 5/5 (SetClothes.setmabu). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(57, 'Công dụng: option bộ Đường Tăng - SetClothes.setduongtang++ khi đủ 5/5. Cách dùng: param 0/1/món. Điều kiện: đủ 5/5. LƯU Ý: tên option đang TRỐNG trong DB, nên cập nhật NAME để hiển thị đúng.'),
(58, 'Công dụng: option bộ Đường Tăng SS - SetClothes.setduongtangss++ khi đủ 5/5. Cách dùng: param 0/1/món. Điều kiện: đủ 5/5. LƯU Ý: tên option đang TRỐNG trong DB.'),
(59, 'Công dụng: nhãn Thuộc Tính Cơ Bản - đánh dấu nhóm thuộc tính cơ bản (vd nhẫn cưới sự kiện EventKetHon). Cách dùng: param 1-2. Điều kiện: hiển thị nhóm, không cộng chỉ số.'),
(60, 'Công dụng: nhãn Thuộc Tính Bộ - đánh dấu nhóm thuộc tính bộ. Cách dùng: param 1-2. Điều kiện: hiển thị.'),
(61, 'Công dụng: nhãn Thuộc Tính Phụ - đánh dấu nhóm thuộc tính phụ. Cách dùng: param 1-2. Điều kiện: hiển thị.'),
(62, 'Công dụng: phục hồi thể lực theo % (item phục hồi stamina). Cách dùng: param = % thể lực hồi. Điều kiện: dùng/mặc theo vật phẩm; không nằm trong NPoint.addOption.'),
(63, 'Công dụng: hiển thị HSD còn lại theo NGÀY (đếm ngược client). Cách dùng: param = số ngày. Điều kiện: vật phẩm có hạn.'),
(64, 'Công dụng: hiển thị HSD còn lại theo GIỜ. Cách dùng: param = số giờ. Điều kiện: vật phẩm có hạn.'),
(65, 'Công dụng: hiển thị HSD còn lại theo PHÚT. Cách dùng: param = số phút. Điều kiện: vật phẩm có hạn.'),
(66, 'Công dụng: bộ Sét Dragon - +1500% SĐ khi đủ 5/5 (SetClothes.setsaga). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5 trên 5 slot đầu.'),
(67, 'Công dụng: đánh dấu vật phẩm Sự Kiện Đi Biển (EventKetHon gán lên nhẫn cưới). Cách dùng: param 0/1. Điều kiện: vật phẩm sự kiện, không cộng chỉ số.'),
(68, 'Công dụng: đánh dấu Linh Khí (bậc khí giới 1). Cách dùng: param 0/1 hoặc bậc. Điều kiện: hiển thị bậc, điều kiện nâng bậc khí giới.'),
(69, 'Công dụng: đánh dấu Tiên Khí (bậc khí giới 2). Cách dùng: param như LINH KHÍ. Điều kiện: điều kiện nâng bậc.'),
(70, 'Công dụng: đánh dấu Đế Khí (bậc khí giới 3). Cách dùng: param như trên. Điều kiện: điều kiện nâng bậc.'),
(71, 'Công dụng: đánh dấu Thánh Khí (bậc khí giới cao nhất). Cách dùng: param như trên. Điều kiện: điều kiện nâng bậc.'),
(72, 'Công dụng: Cấp độ vật phẩm (boss/rương random 1-16 theo Util.randDoTL). Cách dùng: param = cấp, vd 1-16. Điều kiện: hiển thị cấp để so sánh/nâng cấp.'),
(73, 'Công dụng: watermark DragonBallSaga.vn; server DÙNG option này (param 0) làm option rỗng mặc định cho item không có option (InventoryService.addItemList). Cách dùng: param 0. Điều kiện: tự động thêm khi item chưa có option.'),
(74, 'Công dụng: đánh dấu vật phẩm Đã ép (đã ép/phúc hợp trang bị). Cách dùng: param 0/1. Điều kiện: hiển thị, điều kiện nâng cấp.'),
(75, 'Công dụng: đánh dấu bộ Đã Kích Hoạt (Util gán 75 param 1 khi sinh đồ - cờ set kích hoạt). Cách dùng: param 1. Điều kiện: vật phẩm đã kích hoạt.'),
(76, 'Công dụng: cờ VIP trên vật phẩm. Cách dùng: param = mức VIP hoặc 1. Điều kiện: chỉ vật phẩm VIP; hiển thị/điều kiện sử dụng.'),
(77, 'Công dụng: tăng % HP tối đa (NPoint case 77: tlHp += param x opt77_factor/100, hệ số mặc định 10). Cách dùng: param = % theo tên option; server quy đổi qua hệ số - test param thực tế. Điều kiện: mặc.'),
(78, 'Công dụng: hiển thị % Sức Hủy Diệt theo tên option. Ghi chú: không có trong NPoint.addOption - chủ yếu nhãn hiển thị; dame thật dùng option 50/147/239. Cách dùng: param = % hiển thị.'),
(79, 'Công dụng: +% sức đánh cho ĐỆ TỬ (pet) khi sư phụ mặc. Cách dùng: param = %. Điều kiện: có đệ tử; không nằm trong NPoint.addOption của người chơi (xem hệ thống pet).'),
(80, 'Công dụng: hồi % HP mỗi 30 giây (NPoint case 80: tlHpHoi += param, giới hạn 100). Cách dùng: param = % HP hồi mỗi 30s. Điều kiện: mặc; không vượt 100.'),
(81, 'Công dụng: hồi % KI mỗi 30 giây (NPoint case 81: tlMpHoi, giới hạn 100). Cách dùng: param = % KI hồi mỗi 30s. Điều kiện: mặc.'),
(82, 'Công dụng: passive - không bị quái chủ động đánh và giảm 20% sát thương khi bị đánh (theo tên). Cách dùng: param 0/1. Điều kiện: mặc; không cộng qua NPoint.addOption.'),
(83, 'Công dụng: passive - tăng 20% sức mạnh và tiềm năng nhận được khi đánh quái (theo tên). Cách dùng: param 0/1. Điều kiện: mặc; không nằm trong NPoint.addOption.'),
(84, 'Công dụng: bay không tốn KI (theo tên). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm bay/cánh, hiệu ứng áp khi nhân vật bay.'),
(85, 'Công dụng: bay và phục hồi KI (theo tên). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm bay.'),
(86, 'Công dụng: cờ Ký gửi vàng - vật phẩm giao dịch ký gửi bằng VÀNG (ConsignShopService kiểm option 86/87). Cách dùng: param 0/1. Điều kiện: hệ thống kinh doanh ký gửi.'),
(87, 'Công dụng: cờ Ký gửi ngọc - ký gửi bằng NGỌC (ConsignShopService). Cách dùng: param 0/1. Điều kiện: hệ thống kinh doanh ký gửi.'),
(88, 'Công dụng: cộng % kinh nghiệm khi đánh quái (NPoint case 88: tlTNSM). Cách dùng: param = % exp. Điều kiện: mặc; chỉ áp dụng đánh quái.'),
(89, 'Công dụng: bay và phục hồi cả HP, KI (theo tên; ItemService cũng gán 89 cho đồ sự kiện kèm option 30 và HSD). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm bay/sự kiện.'),
(90, 'Công dụng: vật phẩm thả xuống đất tặng người khác sẽ mang lại MAY MẮN cho người nhặt (theo tên). Cách dùng: param 0/1. Điều kiện: thả đồ/tặng.'),
(91, 'Công dụng: mở ra để nhận MAY MẮN (rương may mắn). Cách dùng: param 0/1. Điều kiện: dùng vật phẩm để mở.'),
(92, 'Công dụng: chúc tết bang hội và mọi người kèm pháo hoa (vật phẩm tết). Cách dùng: param 0/1. Điều kiện: dùng vào dịp tết/sự kiện.'),
(93, 'Công dụng: hạn sử dụng theo NGÀY - server tỉ lệ gán HSD 1-3 ngày cho đồ sự kiện (ItemService 95%), TabShopSoHuu và ItemService kiểm để hiển thị. Cách dùng: param = số ngày. Điều kiện: hết hạn mất hiệu lực.'),
(94, 'Công dụng: tăng % giáp (NPoint case 94: tlGiap += param, giảm % sát thương nhận vào). Cách dùng: param = % giáp. Điều kiện: mặc.'),
(95, 'Công dụng: hút % sinh lực (HP) mỗi đòn đánh (NPoint case 95: tlHutHp). Cách dùng: param = % hút HP. Điều kiện: mặc, áp khi đánh trúng mục tiêu.'),
(96, 'Công dụng: hút % mana (KI) mỗi đòn đánh (NPoint case 96: tlHutMp). Cách dùng: param = % hút KI. Điều kiện: mặc.'),
(97, 'Công dụng: phản % sát thương nhận vào (NPoint case 97: tlPST). Cách dùng: param = % phản sát thương. Điều kiện: mặc; thay thế option 15.'),
(98, 'Công dụng: xuyên % giáp đòn chưởng (NPoint case 98: tlxgc). Cách dùng: param = % xuyên giáp chưởng. Điều kiện: mặc, áp khi đánh chưởng.'),
(99, 'Công dụng: xuyên % giáp đòn cận chiến (NPoint case 99: tlxgcc). Cách dùng: param = % xuyên giáp cận. Điều kiện: mặc, áp khi đánh cận.'),
(100, 'Công dụng: cộng % vàng rơi từ quái (NPoint case 100: tlGold). Cách dùng: param = % vàng thêm. Điều kiện: mặc, đánh quái.'),
(101, 'Công dụng: cộng % tiềm năng và sức mạnh nhận được (NPoint case 101: tlTNSM). Cách dùng: param = % TNSM. Điều kiện: mặc; cộng dồn nhiều nguồn.'),
(102, 'Công dụng: hiển thị số Sao Pha Lê (vật liệu pha lê - liên quan option 110 dò pha lê và 228 cường hóa ô sao). Cách dùng: param = số sao. Điều kiện: hiển thị vật liệu.'),
(103, 'Công dụng: tăng % KI tối đa (NPoint case 103: tlMp += param x opt103_factor/100, hệ số mặc định 10). Cách dùng: param = % theo tên; thực nhận khoảng param chia 10 (%). Điều kiện: mặc.'),
(104, 'Công dụng: biến % sát thương đánh quái thành HP hút về (NPoint case 104: tlHutHpMob). Cách dùng: param = % hút HP từ quái. Điều kiện: mặc, đánh quái.'),
(105, 'Công dụng: vô hình khi không đánh quái và boss (NPoint case 105: wearingVoHinh). Cách dùng: param 0/1. Điều kiện: mặc; tự động bật khi chưa tấn công.'),
(106, 'Công dụng: chống lạnh - không bị ảnh hưởng bởi cái lạnh (NPoint case 106: isKhongLanh). Cách dùng: param 0/1. Điều kiện: mặc, map/hoạt động lạnh.'),
(107, 'Công dụng: số Sao Pha Lê trên vật phẩm sự kiện (EventBikip gán param 1-8). Cách dùng: param = số sao. Điều kiện: vật phẩm sự kiện, dùng cho nâng/phá sao.'),
(108, 'Công dụng: cộng % né đòn (NPoint case 108: tlNeDon). Cách dùng: param = % né. Điều kiện: mặc; thay thế option 17.'),
(109, 'Công dụng: giảm % HP khi ở Ô Dơ/Hôi (NPoint case 109: tlHpGiamODo). Cách dùng: param = % giảm HP. Điều kiện: mặc, áp theo cơ chế ô dơ.'),
(110, 'Công dụng: cờ Dò pha lê - bật khả năng dò pha lê khi mặc (NPoint case 110: isDoSPL). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm.'),
(111, 'Công dụng: đánh dấu bộ/sự kiện Sét Thiên Sứ. Cách dùng: param 0/1. Điều kiện: hiển thị, không cộng chỉ số trong NPoint.'),
(112, 'Công dụng: giảm % giá khi mua Avatar hoặc Cải Trang (theo tên). Cách dùng: param = % giảm giá. Điều kiện: áp khi mua tại shop avatar/cải trang.'),
(113, 'Công dụng: vật phẩm Ném cho Sói Hẹc Quyn (sự kiện/nhiệm vụ). Cách dùng: param 0/1. Điều kiện: dùng khi làm nhiệm vụ sự kiện tương ứng.'),
(114, 'Công dụng: cộng % tốc độ chạy (NPoint case 114 dùng chung 16/148: tlSpeed). Cách dùng: param = % (mỗi 100 cộng thêm = 1 cấp tốc). Điều kiện: mặc.'),
(115, 'Công dụng: đánh dấu bộ/sự kiện Sét Hủy Diệt. Cách dùng: param 0/1. Điều kiện: hiển thị.'),
(116, 'Công dụng: kháng Thái Dương Hạ San (NPoint case 116: khangTDHS - miễn/chống hiệu ứng TDHS). Cách dùng: param 0/1. Điều kiện: mặc.'),
(117, 'Công dụng: cộng % SĐ đẹp cho bản thân và người xung quanh (NPoint case 117: tlSexyDame - chỉ lấy param LỚN NHẤT, không cộng dồn). Cách dùng: param = %. Điều kiện: mặc; người xung quanh nhận theo param lớn nhất.'),
(118, 'Công dụng: hiệu ứng kỹ năng - tới ngay mục tiêu và gây choáng # mili giây. Cách dùng: param = số mili giây. Điều kiện: option đánh dấu cho skill/sự kiện, không cộng chỉ số.'),
(119, 'Công dụng: hiệu ứng - gây mù người xung quanh trong # giây. Cách dùng: param = giây. Điều kiện: đánh dấu skill/sự kiện.'),
(120, 'Công dụng: hiệu ứng - ra đòn sau # giây (delay). Cách dùng: param = giây. Điều kiện: skill/sự kiện.'),
(121, 'Công dụng: hiệu ứng Ru Ngủ mục tiêu trong # giây. Cách dùng: param = giây. Điều kiện: skill/sự kiện.'),
(122, 'Công dụng: hiệu ứng Bảo vệ trong # giây. Cách dùng: param = giây. Điều kiện: skill/sự kiện.'),
(123, 'Công dụng: hiệu ứng Trói Gô mục tiêu trong # giây. Cách dùng: param = giây. Điều kiện: skill/sự kiện.'),
(124, 'Công dụng: debuff - mục tiêu tỉnh giấc bị yếu đi, trừ #% sức đánh trong 10 giây. Cách dùng: param = % giảm SĐ. Điều kiện: sau khi bị Ru Ngủ (option 121).'),
(125, 'Công dụng: tăng và hồi % HP tạm thời cho bản thân và xung quanh trong 30 giây. Cách dùng: param = %. Điều kiện: hiệu ứng có thời hạn 30s.'),
(126, 'Công dụng: biến Sôcôla khiến mục tiêu yếu đi, trừ #% sức đánh trong 30 giây. Cách dùng: param = %. Điều kiện: hiệu ứng 30s.'),
(127, 'Công dụng: SET Cày - +80% ST Kaioken khi đủ 5/5 (SetClothes case 127). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5 trên 5 slot đầu, trùng option trong 1 món chỉ đếm 1.'),
(128, 'Công dụng: SET Cày - +100% STQCKK khi đủ 5/5 (SetClothes case 128). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(129, 'Công dụng: SET Cày - +100% ST Kame khi đủ 5/5 (SetClothes case 129). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(130, 'Công dụng: SET Cày - +100% KI khi đủ 5/5 (SetClothes case 130). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(131, 'Công dụng: SET Cày - +80% ST Liên hoàn khi đủ 5/5 (SetClothes case 131). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(132, 'Công dụng: SET Cày - +100% ST Đẻ Trứng khi đủ 5/5 (SetClothes case 132). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(133, 'Công dụng: SET Cày - +100% ST đấm Galick khi đủ 5/5 (SetClothes case 133). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(134, 'Công dụng: SET Cày - x5 thời gian hóa khỉ khi đủ 5/5 (SetClothes case 134). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(135, 'Công dụng: SET Cày - +80% HP khi đủ 5/5 (SetClothes case 135). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(136, 'Công dụng: SET Sao - 99 Sao: +15K% HP, KI, SD khi đủ 5/5 (SetClothes setkichhoat99sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(137, 'Công dụng: SET Sao - 200 Sao: +25K% HP, KI, SD khi đủ 5/5 (setkichhoat200sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(138, 'Công dụng: SET Sao - 300 Sao: +50K% khi đủ 5/5 (setkichhoat300sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(139, 'Công dụng: SET Sao - 500 Sao: +150K% khi đủ 5/5 (setkichhoat500sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(140, 'Công dụng: SET Sao - 700 Sao: +280K% khi đủ 5/5 (setkichhoat700sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(141, 'Công dụng: SET Sao - 18 Sao: +500% khi đủ 5/5 (setkichhoat18sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(142, 'Công dụng: SET Sao - 30 Sao: +1K% khi đủ 5/5 (setkichhoat30sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(143, 'Công dụng: SET Sao - 45 Sao: +2K5% khi đủ 5/5 (setkichhoat45sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(144, 'Công dụng: SET Sao - 65 Sao: +5K% khi đủ 5/5 (setkichhoat65sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(145, 'Công dụng: SET Sao - 999 Sao: +500K% khi đủ 5/5 (setkichhoat999sao). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(146, 'Công dụng: Tinh Luyện 16 - +16 và +1K% STCM khi đủ 5/5 (SetClothes.tinhluyen16). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(147, 'Công dụng: cộng thẳng % sức đánh (NPoint case 147: tlDame += param, 1-1). Cách dùng: param = % SĐ. Điều kiện: mặc/Card/Cung Mệnh.'),
(148, 'Công dụng: cộng % tốc chạy (NPoint case 148 dùng chung 16/114: tlSpeed). Cách dùng: param = %. Điều kiện: mặc.'),
(149, 'Công dụng: SET Ngũ Hành Thanh Long - +500% KI khi đủ 5/5 (đếm qua setCount, bonus đọc từ bảng set_config - SetConfigService). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(150, 'Công dụng: SET Chu Tước - +500% HP khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(151, 'Công dụng: SET Bạch Hổ - +250% SD khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(152, 'Công dụng: SET Huyền Vũ - +500% DEF khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(153, 'Công dụng: SET Kim - +5M SD khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5. Ghi chú: NPoint case 153 map cũ là tlBom (% nổ khi chết) - đừng đặt param lớn.'),
(154, 'Công dụng: SET Mộc - +10M HP khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(155, 'Công dụng: SET Thổ - +10M KI khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(156, 'Công dụng: SET Thủy - +10M DEF khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(157, 'Công dụng: SET Hỏa - +100% STCM khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(158, 'Công dụng: nhãn Thuộc Tính Thường - đánh dấu nhóm thuộc tính thường. Cách dùng: param theo nhóm. Điều kiện: hiển thị.'),
(159, 'Công dụng: số đòn chưởng cơ bản mỗi phút (NPoint case 159: xChuong = param). Cách dùng: param = số đòn chưởng/phút. Điều kiện: mặc.'),
(160, 'Công dụng: cộng % TN, SM cho ĐỆ TỬ khi sư phụ mặc (NPoint case 160: tlTNSMPet). Cách dùng: param = %. Điều kiện: có đệ tử.'),
(161, 'Công dụng: thêm # ngọc mỗi ngày khi đánh quái (quyền lợi theo ngày, theo tên). Cách dùng: param = số ngọc/ngày. Điều kiện: đánh quái; không nằm trong NPoint.addOption.'),
(162, 'Công dụng: Cute hồi % KI mỗi giây cho bản thân và xung quanh (NPoint case 162: mpHoiCute). Cách dùng: param = % KI/giây. Điều kiện: mặc; người xung quanh nhận theo người mặc.'),
(163, 'Công dụng: hiệu ứng - biến người xung quanh thành Bí Ngô (sự kiện Halloween). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm sự kiện.'),
(164, 'Công dụng: đổi vật phẩm bằng # điểm sự kiện (giá đổi ở NPC/sự kiện). Cách dùng: param = số điểm sự kiện cần có. Điều kiện: đủ điểm và đúng NPC đổi quà sự kiện.'),
(165, 'Công dụng: cơ hội gây % sát thương LỬA khi cận chiến trúng quái (proc lửa). Cách dùng: param = % cơ hội. Điều kiện: mặc, đánh cận quái.'),
(166, 'Công dụng: +% sức đánh lên quái khi bay với Cải Trang Tàu Pảy Pảy. Cách dùng: param = %. Điều kiện: đang bay và mặc Cải Trang Tàu Pảy Pảy.'),
(167, 'Công dụng: hiệu ứng - tạo không khí lạnh quanh người (aura). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm.'),
(168, 'Công dụng: hiệu ứng - hấp thụ sức mạnh rồi bộc phá (kỹ năng/sự kiện). Cách dùng: param 0/1. Điều kiện: đánh dấu skill, không cộng chỉ số.'),
(169, 'Công dụng: cơ hội ĐẦU ĐỐC đối thủ khi đánh trúng (proc độc). Cách dùng: param = % cơ hội (nếu có số). Điều kiện: mặc, PvP/PVE theo cấu hình.'),
(170, 'Công dụng: +% sức đánh lên quái khi bay với Cải Trang nhà Fide. Cách dùng: param = %. Điều kiện: đang bay và mặc Cải Trang nhà Fide.'),
(171, 'Công dụng: hiển thị số lượng dạng #K (x1000) cho vật phẩm tiền tệ lớn. Cách dùng: param = số nghìn, vd 500 = 500.000. Điều kiện: hiển thị.'),
(172, 'Công dụng: tỉ lệ Tu Tiên Đột Phá % (theo tên). Cách dùng: param = % đột phá. Điều kiện: hệ thống tu tiên/tẩy task tu tiên.'),
(173, 'Công dụng: hồi % HP và KI cho bản thân và ĐỒNG ĐỘI (NPoint case 173: tlHpHoiBanThanVaDongDoi). Cách dùng: param = % hồi. Điều kiện: mặc, theo chu kỳ hồi 30s.'),
(174, 'Công dụng: đánh dấu Sự Kiện Năm # (năm/đợt sự kiện). Cách dùng: param = năm. Điều kiện: hiển thị/điều kiện năm.'),
(175, 'Công dụng: giảm % thời gian bị MÙ (theo tên). Cách dùng: param = % giảm. Điều kiện: mặc, áp khi bị mù.'),
(176, 'Công dụng: hiệu ứng chủ động - ở gần đủ 5 loại: +20% sức đánh và +50% tốc độ chạy. Cách dùng: param 0/1 (option $ đặc biệt). Điều kiện: đứng gần đủ 5 loại theo quy định.'),
(177, 'Công dụng: ở gần Mabư mập: tối đa +2% tất cả chỉ số. Cách dùng: param = % theo mốc. Điều kiện: đứng gần Mabư mập, cộng tối đa 2%.'),
(178, 'Công dụng: hồi % KI mỗi 10 giây (theo tên). Cách dùng: param = % KI mỗi 10s. Điều kiện: mặc, chu kỳ 10 giây.'),
(179, 'Công dụng: +2% sức đánh, tối đa 10% khi ở gần Cải Trang tộc Demons Frost. Cách dùng: param = % theo mốc. Điều kiện: gần CT Demons Frost, cap 10%.'),
(180, 'Công dụng: +% sức đánh khi ở gần Cải Trang Black Gohan Rose. Cách dùng: param = %. Điều kiện: gần CT Black Gohan Rose (xem cap theo cấu hình).'),
(181, 'Công dụng: khi dịch chuyển tức thời được +% sát thương. Cách dùng: param = % sát thương thêm sau dịch chuyển. Điều kiện: mặc, vừa dịch chuyển.'),
(182, 'Công dụng: +% sát thương cho ĐỆ TỪ TRỨNG (đẻ trứng). Cách dùng: param = %. Điều kiện: có đệ từ trứng, khi đánh.'),
(183, 'Công dụng: giảm % thời gian hồi Khiên Năng Lượng. Cách dùng: param = % giảm. Điều kiện: mặc, dùng khiên.'),
(184, 'Công dụng: +% sức đánh, tối đa 10% khi ở gần Gohan xanh, Poc đỏ, Arale búp bê. Cách dùng: param = % theo mốc. Điều kiện: gần các CT kể trên, cap 10%.'),
(185, 'Công dụng: gán/hiển thị HSD theo GIỜ (mở rộng option 93). Cách dùng: param = số giờ. Điều kiện: vật phẩm có hạn dùng theo giờ.'),
(186, 'Công dụng: hiệu ứng - biến thành kẹo 30 giây (sự kiện). Cách dùng: param 0/1. Điều kiện: mặc vật phẩm sự kiện.'),
(187, 'Công dụng: giảm # giây thời gian bị MÙ (giảm trừ theo giây). Cách dùng: param = số giây giảm. Điều kiện: mặc, đang bị mù.'),
(188, 'Công dụng: SET Đệ - +20K% ST Kame khi đủ 5/5 (đếm qua setCount, bonus từ set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(189, 'Công dụng: SET Đệ - +20K% ST Masenco khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(190, 'Công dụng: SET Đệ - +20K% ST Antomic khi đủ 5/5 (set_config). Cách dùng: param 0/1/món. Điều kiện: đủ 5/5.'),
(191, 'Công dụng: né CHÍ MẠNG - giảm % bị đánh trúng chí mạng (theo tên). Cách dùng: param = % né chí mạng. Điều kiện: mặc.'),
(192, 'Công dụng: +% chí mạng hiển thị. Ghi chú: cộng chí mạng thật server dùng option 14 (critAdd). Cách dùng: param = % hiển thị. Điều kiện: mặc, ưu tiên option 14.'),
(193, 'Công dụng: +% sức đánh, tối đa 11% khi ở gần Cải trang cầu thủ khác. Cách dùng: param = % theo mốc. Điều kiện: gần CT cầu thủ, cap 11%.'),
(194, 'Công dụng: +% sức đánh, tối đa 10% khi ở gần Cải trang hè khác. Cách dùng: param = % theo mốc. Điều kiện: gần CT hè, cap 10%.'),
(195, 'Công dụng: +% sức đánh, tối đa 10% khi ở gần Cải trang siêu nhân khác. Cách dùng: param = % theo mốc. Điều kiện: gần CT siêu nhân, cap 10%.'),
(196, 'Công dụng: xinh +% sức đánh, tối đa 18% khi ở gần Cải trang Thỏ khác. Cách dùng: param = % theo mốc. Điều kiện: gần CT Thỏ, cap 18%.'),
(197, 'Công dụng: +% tấn công lên TỘC XAYDA khi PK liên tộc (type 7). Cách dùng: param = % SĐ thêm. Điều kiện: mục tiêu là tộc Xayda.'),
(198, 'Công dụng: giảm % sát thương nhận từ TỘC TRÁI ĐẤT (type 7). Cách dùng: param = % giảm. Điều kiện: bị tộc Trái Đất đánh.'),
(199, 'Công dụng: giảm % sát thương nhận từ TỘC NAMÉC (type 7). Cách dùng: param = % giảm. Điều kiện: bị tộc Naméc đánh.'),
(200, 'Công dụng: giảm % sát thương nhận từ TỘC XAYDA (type 7). Cách dùng: param = % giảm. Điều kiện: bị tộc Xayda đánh.'),
(201, 'Công dụng: +% tấn công khi ở gần 2 thành viên bang (type 7). Cách dùng: param = %. Điều kiện: có ít nhất 2 thành viên bang ở gần.'),
(202, 'Công dụng: +% HP khi ở gần 2 thành viên bang (type 7). Cách dùng: param = %. Điều kiện: ít nhất 2 thành viên bang ở gần.'),
(203, 'Công dụng: +% KI khi ở gần 2 thành viên bang (type 7). Cách dùng: param = %. Điều kiện: ít nhất 2 thành viên bang ở gần.'),
(204, 'Công dụng: +% tấn công lên BOSS (NPoint case 204: dameBoss += param). Cách dùng: param = % SĐ thêm khi đánh boss. Điều kiện: mặc, đánh boss.'),
(205, 'Công dụng: đi cùng Cải Trang Diệt Quỷ: +% SĐ, tối đa 18% (type 7). Cách dùng: param = % theo mốc. Điều kiện: ở gần người mặc CT Diệt Quỷ, cap 18%.'),
(206, 'Công dụng: tỉ lệ VẬT PHẨM HIẾM rơi từ QUÁI (+%). Cách dùng: param = % tỉ lệ. Điều kiện: mặc, đánh quái (ảnh hưởng roll rơi đồ hiếm).'),
(207, 'Công dụng: tỉ lệ VẬT PHẨM HIẾM rơi từ BOSS (+%) - Util gán 207 cho đồ rơi boss. Cách dùng: param = % tỉ lệ. Điều kiện: mặc, đánh boss.'),
(208, 'Công dụng: đánh dấu Trang bị ĐÃ CHUYỂN HÓA. Cách dùng: param 0/1. Điều kiện: hiển thị, điều kiện chuyển hóa/nâng cấp.'),
(209, 'Công dụng: thống kê Bị rớt cấp # lần (số lần bị giảm cấp). Cách dùng: param = số lần. Điều kiện: hiển thị.'),
(210, 'Công dụng: cộng thêm # Thuộc Tính Thường (mở rộng nhóm thuộc tính thường). Cách dùng: param = số thuộc tính. Điều kiện: vật phẩm có nhóm thuộc tính thường.'),
(211, 'Công dụng: tiến độ Giám định #/5; đồng thời NPoint case 211 đếm setltdb - mặc đủ 5 món có option này sẽ bật cờ Linh Thủy Đánh Bạc. Cách dùng: param = số lần/progress. Điều kiện: giám định 5/5 hoặc đeo 5 món.'),
(212, 'Công dụng: Độ bền #/1000 của trang bị. Cách dùng: param = độ bền còn lại (1000 = đầy). Điều kiện: hết độ bền thì vật phẩm hỏng (xem option 252).'),
(213, 'Công dụng: Giá bán lại của vật phẩm (triệu vàng). Cách dùng: param = số triệu vàng NPC mua lại. Điều kiện: bán cho NPC/shop.'),
(214, 'Công dụng: tăng % PHẠM VI tuyệt kỹ (mở rộng vùng kỹ năng). Cách dùng: param = % mở rộng. Điều kiện: mặc, dùng tuyệt kỹ.'),
(215, 'Công dụng: tăng SỐ LƯỢNG MỤC TIÊU của tuyệt kỹ/kỹ năng. Cách dùng: param = số mục tiêu thêm. Điều kiện: mặc, dùng kỹ năng đa mục tiêu.'),
(216, 'Công dụng: +% sát thương cho TUYỆT KỸ. Cách dùng: param = % sát thương thêm. Điều kiện: mặc, dùng tuyệt kỹ.'),
(217, 'Công dụng: đánh dấu CHƯA GIÁM ĐỊNH - vật phẩm chưa giám định, chỉ số ẩn. Cách dùng: param 0/1. Điều kiện: trước khi giám định (xem option 211).'),
(218, 'Công dụng: đếm số lần Đập Xịt; Trade.java: option 218 (cùng 30) làm vật phẩm KHÔNG giao dịch được. Cách dùng: param = số lần đập xịt. Điều kiện: cấm GD khi còn option này.'),
(219, 'Công dụng: đếm SỐ LẦN TẨY option của vật phẩm (hệ thống tẩy/luyện lại chỉ số). Cách dùng: param = số lần đã tẩy. Điều kiện: hiển thị/điều kiện nâng tẩy.'),
(220, 'Công dụng: hiển thị TIẾN ĐỘ Hoàn thành #% (nhiệm vụ/sự kiện/cường hóa). Cách dùng: param = % hoàn thành. Điều kiện: hiển thị.'),
(221, 'Công dụng: hồi % HP và KI mỗi 30 giây cho bản thân và ĐỒNG BANG. Cách dùng: param = % hồi mỗi 30s. Điều kiện: mặc, cùng bang nhận theo người mặc.'),
(222, 'Công dụng: chu kỳ 120 giây - kích nộ, +% sức đánh trong 30 giây. Cách dùng: param = % SĐ khi kích nộ. Điều kiện: mặc, tự động theo chu kỳ 120s/30s.'),
(223, 'Công dụng: chu kỳ 120 giây - kích hồi, +% HP trong 30 giây. Cách dùng: param = % HP hồi khi kích hồi. Điều kiện: mặc, chu kỳ 120s/30s.'),
(224, 'Công dụng: giảm thời gian cooldown của TẤT CẢ kỹ năng về 0,1 giây. Cách dùng: param 0/1. Điều kiện: mặc (spam skill liên tục - cẩn thận cân bằng).'),
(225, 'Công dụng: giảm # giây bị PHONG ẤN của Ma Phong Ba. Cách dùng: param = số giây giảm. Điều kiện: đang bị Ma Phong Ba phong ấn.'),
(226, 'Công dụng: Cute +% sức đánh cho mình và người xung quanh (theo tên). Cách dùng: param = %. Điều kiện: mặc, aura áp cho người gần.'),
(227, 'Công dụng: giảm % tác dụng của các đòn KHỐNG CHẾ khi dùng Khiên Năng Lượng. Cách dùng: param = % giảm. Điều kiện: đang dùng khiên.'),
(228, 'Công dụng: đánh dấu ĐÃ CƯỜNG HÓA tới ô Sao Pha Lê # (tiến độ cường hóa). Cách dùng: param = số ô đã cường hóa. Điều kiện: hệ thống cường hóa sao pha lê (liên quan 102/107/110).'),
(229, 'Công dụng: Lạnh gây giảm % HP, KI mỗi 30 giây cho người xung quanh. Cách dùng: param = % giảm mỗi 30s. Điều kiện: mặc, có người quanh (aura lạnh).'),
(230, 'Công dụng: cộng # TRIỆU tiềm năng và sức mạnh. Cách dùng: param = số triệu (vd 5 = 5.000.000 TN và SM). Điều kiện: mặc/được cấp.'),
(231, 'Công dụng: cờ Có Tỉ Lệ Vĩnh Viễn Hoặc Hạn - vật phẩm khi rơi/được cấp có tỉ lệ vĩnh viễn hoặc có hạn (Util gán 231; ShopService/InventoryService kiểm). Cách dùng: param = mức tỉ lệ. Điều kiện: nhận đồ từ boss/shop/sự kiện.'),
(232, 'Công dụng: đếm SỐ LẦN GIAO DỊCH CÒN LẠI của vật phẩm. Cách dùng: param = số lần GD còn lại. Điều kiện: giao dịch nhiều lần, về 0 thì hết GD.'),
(233, 'Công dụng: đánh dấu thuộc tính Fam Thiên Đạo Pháp Tắc. Cách dùng: param theo mức thuộc tính. Điều kiện: hệ thống Fam/quyền năng.'),
(234, 'Công dụng: đánh dấu thuộc tính Fam Địa Đạo Luân Hồi (type 9). Cách dùng: param theo mức. Điều kiện: hệ thống Fam/quyền năng.'),
(235, 'Công dụng: đếm SỐ LẦN KÝ GỬI CÒN LẠI của vật phẩm. Cách dùng: param = số lần ký gửi còn lại. Điều kiện: hệ thống ký gửi (cùng 86/87/37).'),
(236, 'Công dụng: cộng % MAY MẮN (ảnh hưởng tỉ lệ rơi hiếm/rương may mắn). Cách dùng: param = % may mắn, thường 10-50. Điều kiện: mặc; RewardService có roll option 236 cho đồ thưởng.'),
(237, 'Công dụng: cộng # THUỘC TÍNH VIP (Util gán 237 param 5 cho đồ VIP). Cách dùng: param = số thuộc tính VIP. Điều kiện: vật phẩm VIP; hiển thị/điều kiện kích hoạt.'),
(238, 'Công dụng: cộng # THUỘC TÍNH HUYỀN ẢO. Cách dùng: param = số thuộc tính huyền ảo. Điều kiện: vật phẩm hiếm; hiển thị/điều kiện kích hoạt.'),
(239, 'Công dụng: Xứ Mệnh cộng % sức đánh (NPoint case 239: tlDame += param, 1-1). Cách dùng: param = % SĐ. Điều kiện: vật phẩm Xứ Mệnh đang mặc.'),
(240, 'Công dụng: Xứ Mệnh Khảm cộng % sức đánh (NPoint case 240: tlDame += param, 1-1). Cách dùng: param = % SĐ. Điều kiện: Xứ Mệnh đã khảm, đang mặc.'),
(241, 'Công dụng: đánh dấu CHƯA KÍCH HOẠT chỉ số - chỉ số ẩn chưa bật. Cách dùng: param 0/1. Điều kiện: trước khi kích hoạt (xem 242).'),
(242, 'Công dụng: đánh dấu ĐÃ KÍCH HOẠT chỉ số - chỉ số đã bật. Cách dùng: param 0/1. Điều kiện: sau khi kích hoạt (đổi từ 241).'),
(243, 'Công dụng: đánh dấu bông tai PORATA (hợp thể Porata - NPoint đọc bông tai cấp 2 khi fusion lớn hơn Porata). Cách dùng: param 0/1. Điều kiện: hợp thể Porata trở lên.'),
(244, 'Công dụng: đánh dấu ĐƯỢC GIAO DỊCH - ghi rõ vật phẩm này được phép GD (trái với 30/218). Cách dùng: param 0/1. Điều kiện: hiển thị; GD vẫn cần không có 30/218.'),
(245, 'Công dụng: Thiên Tử Mệnh +% STCM (theo tên). Cách dùng: param = % STCM. Điều kiện: vật phẩm mệnh/thiên tử, đang mặc.'),
(246, 'Công dụng: đánh dấu ĐỒ SĂN TỪ BOSS - vật phẩm rơi từ boss. Cách dùng: param 0/1. Điều kiện: hiển thị/điều kiện chế tác (cùng 207/75).'),
(247, 'Công dụng: Kích Sát Boss +% (sát thương thêm khi boss thấp máu/kích sát). Cách dùng: param = % sát thương thêm. Điều kiện: mặc, đánh boss.'),
(248, 'Công dụng: đánh dấu Sự Kiện Năm +# (năm sự kiện trên vật phẩm). Cách dùng: param = số năm/mã sự kiện. Điều kiện: hiển thị/điều kiện năm.'),
(249, 'Công dụng: option ẨN - EventKetHon gán 249 param 1 lên nhẫn; dùng để ẩn/đánh dấu đặc biệt trên client. Cách dùng: param 0/1. Điều kiện: vật phẩm sự kiện, không cộng chỉ số.'),
(250, 'Công dụng: đánh dấu ĐÃ ĐẬP XỊT (trang bị bị đập xịt). Cách dùng: param 0/1. Điều kiện: hiển thị, điều kiện nâng lại (cùng 218).'),
(251, 'Công dụng: option VIP - EventKetHon gán 251 param 1 (nhãn VIP/đặc biệt). Cách dùng: param 0/1. Điều kiện: vật phẩm VIP/sự kiện, không cộng chỉ số.'),
(252, 'Công dụng: đánh dấu HỎNG - vật phẩm hỏng (độ bền về 0, xem 212). Cách dùng: param 0/1. Điều kiện: cần sửa/chữa trước khi dùng.'),
(253, 'Công dụng: đánh dấu Tu Tiên Mãi Đỉnh (trạng thái tu tiên đỉnh cao trên vật phẩm). Cách dùng: param 0/1. Điều kiện: hệ thống tu tiên, hiển thị thành tựu.')
ON DUPLICATE KEY UPDATE cach_dung = VALUES(cach_dung);
