<div class="intro" style="background: #FDF8DA; border-radius: 7px; ">
    <h2 style="font-size:22px;color:664d03;padding:20px 20px;">Nổi Bật</h2>
    <p style="padding: 0 24px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- Server <b><?php echo htmlspecialchars($brandName); ?></b> - tỷ lệ kinh nghiệm <b>x<?php echo $serverRate; ?></b>, sức chứa <?php echo number_format($serverMaxPlayer); ?> người chơi</span></br>- Không cần mở thành viên vẫn chơi game cày cuốc kiếm tiền, đua top được</span></br>- Đăng ký tài khoản, tải game tất cả đều miễn phí</span></br>- <?php echo htmlspecialchars($brandName); ?> hướng tới sự lâu dài, đặt cảm giác trải nghiệm của người chơi lên hàng đầu</span></br>- 20 bảng xếp hạng đua top công khai, dữ liệu lấy trực tiếp từ máy chủ</span></br>- Admin không can thiệp vào game</span></br>- <a href="/chucnang">Xem toàn bộ tính năng &amp; thông tin máy chủ &raquo;</a></span></p>
    <div class="border-danger border-top mt-4"></div>
    <h2 style="font-size:22px;color:664d03;padding:20px 20px;">Giới thiệu</h2>
    <p style="padding: 0 24px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- Thể loại h&agrave;nh động, nhập vai. Trực tiếp điều khiển nh&acirc;n vật h&agrave;nh động. Dễ chơi, dễ điều khiển nh&acirc;n vật. Đồ họa sắc n&eacute;t. C&oacute; phi&ecirc;n bản đồ họa cao cho điện thoại mạnh v&agrave; phi&ecirc;n bản pixel cho m&aacute;y cấu h&igrave;nh thấp.</span><br style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- Cốt truyện b&aacute;m s&aacute;t nguy&ecirc;n t&aacute;c. Người chơi sẽ gặp tất cả nh&acirc;n vật từ Bunma, Quy l&atilde;o kame, Jacky-chun, T&agrave;u Pảy Pảy... cho đến Fide, Pic, Poc, X&ecirc;n, Broly, đội Bojack.</span><br style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- Đặc điểm nổi bật nhất: Tham gia đ&aacute;nh doanh trại độc nh&atilde;n. Tham gia đại hội v&otilde; thuật. Tham gia săn l&ugrave;ng ngọc rồng để mang lại điều ước cho bản th&acirc;n.</span><br style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- Tương th&iacute;ch tất cả c&aacute;c d&ograve;ng m&aacute;y tr&ecirc;n thị trường hiện nay: M&aacute;y t&iacute;nh PC Windows, Điện thoại di động Nokia Java, Android v&agrave; m&aacute;y t&iacute;nh bảng Android.</span></p>
    <div class="text-center pt-3"> <img style="height:90px; width:96px" src="assets/images/skill-01.gif"> <img
            style="height:90px; width:96px" src="assets/images/skill-02.gif"> <img style="height:90px; width:96px"
            src="assets/images/skill-03.gif"> <img style="height:90px; width:96px" src="assets/images/skill-04.gif"> <img
            style="height:90px; width:96px" src="assets/images/skill-05.gif"> </div>
    <div class="border-danger border-top mt-4"></div>
    <h2 style="font-size:22px;color:664d03;padding:20px 20px;">Hướng Dẫn Tân Thủ</h2>
    <p style="padding: 0 24px;"><span style="text-align: left;color: rgb(52, 58, 64);background-color: rgb(255, 232, 209);font-size: 16px;">- 1. Đăng ký tài khoản</span></br><?php echo htmlspecialchars($brandName); ?> sử dụng Tài Khoản riêng, không chung với bất kỳ Trò Chơi nào khác.</span></br>Bạn có thể đăng ký tài khoản miễn phí ngay trong game, hoặc trên trang Diễn Đàn.</span></br>Khi đăng ký, bạn nên sử dụng đúng số điện thoại hoặc email thật của mình.</span></br>Nếu sử dụng thông tin sai, người có số điện thoại hoặc email thật sẽ có thể lấy mật khẩu của bạn.</span></br>Số điện thoại và email của bạn sẽ không hiện ra cho người khác thấy. Admin không bao giờ hỏi mật khẩu của bạn.</span></br>2. Hướng dẫn điều khiển</span></br>Đối với máy bàn phím: Dùng phím mũi tên, phím số, để điều khiển nhân vật. Phím chọn giữa để tương tác.</span></br>Đối với máy cảm ứng: Dùng tay chạm vào màn hình cảm ứng để di chuyển. Chạm nhanh 2 lần vào 1 đối tượng để tương tác.</span></br>Đối với PC: Dùng chuột, click chuột phải để di chuyển, click chuột trái để chọn, click đôi vào đối tượng để tương tác</span></br>3. Một số thông tin căn bản</span></br>- Đậu thần dùng để tăng KI và HP ngay lập tức.</span></br>- Bạn chỉ mang theo người được 10 hạt đậu. Nếu muốn mang nhiều hơn, hãy xin từ bạn bè trong Bang.</span></br>- Tất cả các sách kỹ năng đều có thể học miễn phí tại Quy Lão Kame, khi bạn có đủ điểm tiềm năng.</span></br>- Bạn không thể bay, dùng kỹ năng, nếu hết KI.</span></br>- Tấn công quái vật cùng bạn bè trong Bang sẽ mang lại nhiều điểm tiềm năng hơn đánh một mình.</span></br>- Tập luyện với bạn bè tại khu vực thích hợp sẽ mang lại nhiều điểm tiềm năng hơn đánh quái vật.</span></br>- Khi được nâng cấp, đậu thần sẽ phục hồi nhiều HP và KI hơn.</span></br>- Vào trò chơi đều đặn mỗi ngày để nhận được Ngọc miễn phí.</span></br>- Đùi gà sẽ phục hồi 100% HP, KI. Cà chua phục hồi 100% KI. Cà rốt phục hồi 100% HP.</span></br>- Cây đậu thần kết một hạt sau một thời gian, cho dù bạn đang offline.</span></br>- Sau 3 ngày không tham gia trò chơi, bạn sẽ bị giảm sức mạnh do lười luyện tập.- Bạn sẽ giảm thể lực khi đánh quái, nhưng sẽ tăng lại thể lực khi không đánh nữa.</span></br>- Ngoài ra, bạn có thể tham khảo những thông tin sau để có thể dễ dàng tham gia trò chơi hơn.
</div>